version: "3.9"
services:
  sftpgo:
    container_name: sftpgo
    image: drakken/sftpgo:latest
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "2022:2022"